### ISSUE TITLE
👋🏻  Looking good, how does this differ with Redux Devtool Chrome extension?

### ISSUE THREAD

**Issue by anthowave** [reyraa/reduxMonitor#13]

**Comment by reyraa** [comment]
Thank you. Redux Devtool Chrome extension works only on Chrome and Firefox and the maintainer seem to not have any interest in publishing a version for Safari. I constantly find myself in need of running my apps on Safari. I created this for myself and whoever needs it.

**Comment by Methuselah96** [comment]
Just as a heads up, I'm now maintaining the Redux Devtools Chrome extension and would like to see us add Safari support at some point. I haven't looked into how hard it would be, but it's on my backlog to look into.

**Comment by reyraa** [comment]
@Methuselah96 Sure. Reach out if you had any questions. There are many great projects out there and it'd be great to have several options for Safari too.
